- name: backend setup
  hosts: all
  become: yes
  tasks:
   - name: Disable default Nodejs Version Module
     ansible.builtin.shell: dnf module disable nodejs -y

   - name: Enable Nodejs module for V20
     ansible.builtin.shell: dnf module disable nodejs -y

   - name: Install Nodejs
     ansible.builtin.dnf:
      name: nodejs
      state: installed

   - name: Adding application user
     ansible.builtin.user:
       name: expense

   - name: Clean old directory
     ansible.builtin.file:
       path: /app
       state: absent

   - name: Create App directory
     ansible.builtin.file:
       path: /app
       state: directory

   - name: Download and extract App content
     ansible.builtin.unarchive:
       src: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
       dest: /app
       remote_src: yes

   - name: Download Nodejs dependencies
     community.general.npm:
       path: /app
       state: latest

   - name: Copy backend service file
     ansible.builtin.copy:
       src: backend.service
       dest: /etc/systems/system/backend.service

   - name: Install mysql client
     ansible.builtin.dnf:
       state: installed

   - name: Load schema
     community.mysql.mysql_db:
       state: import
       name: all
       target: /app/schema/backend.sql
       login_user: root
       login_password: ExpenseApp@1
       login_host: mysql-dev.devopssz14.online

   - name: Start Backend service
     ansible.builtin.systemd_service:
       name: backend
       state: restarted
       enabled: yes
       Daemon_reload: yes





