- name: backend setup
  hosts: all
  become: yes
  tasks:
      - name: Disable default Nodejs Version Module
        community.general.dnf_config_manager:
          -name: Nodejs
            state: disabled
