- name: frontend setup
  hosts: all
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
       name: nginx
       state: latest
    - name: Copy expense nginx configuration
      ansible.builtin.copy:
        src:
    - name: Start nginx
      ansible.builtin.systemd_service:
        state: restarted
        name: nginx


       #ahjdhdwjds
