- name: Mysql setup
  hosts: all
  become: yes
  tasks:
    - name: Install Mysql server
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: Start mysql service
      ansible.builtin.systemd_service:
        name: mysqld
        state: started
        enabled: yes

    - name: Setup Mysql Password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1

      # it will fail
      # in project we have to use amazon services for database-rds